# -*- coding: utf-8 -*-
"""Pertemuan 1: Introduction of Python in Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LnlywOo70YE7PdzQmvJ9alJZUz9wIohm
"""

#Introduction of python in data science

# 1. Introduction to python
# 2. Math operations with Numpy
# import numpy
# 3. Data manipulation with Pandas
# import pandas
# 4. Visualization with Matplotlib
# import matplotlib

print("Hello, Wordld")

###############################
# INTRODUCTION TO PYTHON
###############################



#print
print("Hello World")

# This is a comment

#Data types
# string  ex: "Hello world"
# integer ex: 15
# float ex: 3.14
# boolean: True, False

# Variable
x = 15 

#Collection types
# 1. list
numbers = [1, 2, 3, 4, 5]
vowels = ['a', 'i', 'u', 'e', 'o']

# 2. dictionary
# { key: value,}
employee = {'name': 'Elizabeth', 'age':25, 'designation': 'Software Engineer'}


# 3. tuple
x = (1,2,3,4,5)

# 4. sets
fruits = {'apple', 'orange', 'banana'}

x[4]

#Operator
x = int(input("input x = "))
y = int(input("input y = "))


print("x +y = ",x+y) #addition
print(x-y) #substraction
print(x*y) #multiplication
print(x/y) #division
print(x//y) #floor division
print(x%y) #modulus
print(x**y) #exponentiation


#Comparison Operator
print(x==y) #equal
print(x!=y) #not equal
print(x>=y) #greater than and equal
print(x<y) #less than
print(x<=y) #less than and equal

#Logical operator

x = int(input("input x = "))
y = int(input("input y = "))

print(x>0 and y>0)
print(x>0 or y>0)
print(not (x>0 and y>0) )

# If Statement
#
# if condition:
#     statement



a= int(input("input a = "))
b = int(input("input b = "))

if a>b:
  print("{} greater than {}".format(a,b))
else:
  print("{} less than {}".format(a,b))

# Looping

for i in [1,2,3]:
  print(i)

print("\n")

for i in list(range(6)):
  print(i)

print("\n")

for j in list(range(7,12)):
  print(j)

print("\n")

for w in "HelloWorld":
  print(w)

for w in "Hello,World":
  print(w)

# Function

def add(x,y):
  return x+y

def substact(x,y):
  return x-y

def multiple(x,y):
  result = x*y
  return result

def mod(x,y):
  return x % y
  

# def compare(a,b):
#   if a>b:
#     print("{} greater than {}.".format(a,b))
#   else:
#     print("{} less than {}.".format(a,b))

a = substact(3,4)
print(a)

#################################
# MATH OPERATIONS WITH NUMPY
#################################
import numpy as np

numbers = np.array([1, 2, 3, 4]) 

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
# [1 2 3]
# [4 5 6]
# [7 8 9]

print(x.ndim) # ndim returns the number of dimensions of the array.
print(x.size) # size returns the total number of elements of the array.
print(x.shape) # shape returns a tuple of integers that indicate the number of elements stored along each dimension of the array.

#Indexing & Slicing
print(numbers[1])
print(numbers[numbers>1])
x23 = x[1][2]
print(x23)


x = np.array([2, 1, 3])
x = np.append(x, 4) #Add an element 4
x = np.delete(x, 0) #Delete at index 0
x = np.sort(x) #Sort the array


#Array operations
X = np.arange(1, 10)
y = X**2

import numpy as np

numbers = np.array([1, 2, 3, 4]) 

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("numbers = ",numbers)
print('x = ',x)

print(x.ndim)
print(x.size)
print(x.shape)

X = np.arange(1, 10)
print(X)

y = X*2
print(y)

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
x[1][2]

x = np.array([2, 1, 3])
x1 = np.append(x, 4) #Add an element 4
x2 = np.delete(x, 0) #Delete at index 0
x3 = np.sort(x) #Sort the array

print(x1)
print(x2)
print(x3)

#################################################
# DATA MANIPULATION WITH PANDAS
#################################################
import pandas as pd

x = [ 4,  5, 10,  4,  3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

#dictionary
data = {'X':x, 'Y':y}

#create a dataframe
mydata = pd.DataFrame(data, columns=['X','Y'])

#indexing and slicing
mydata['X']
mydata[['X','Y']]
mydata[(mydata['X']>18) & (mydata['Y']>10)]
mydata[(mydata['X']>18) | (mydata['Y']>10)]

#Summary statictics
mydata.describe()

import pandas as pd

x = [ 4,  5, 10,  4,  3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

#dictionary
mydata = {'X':[ 4,  5, 10,  4,  3, 11, 14 , 6, 10, 12], 
        'Y':[21, 19, 24, 17, 16, 25, 24, 22, 21, 21]}

#create a dataframe
mydata = pd.DataFrame(mydata, columns=['X','Y'])
X = mydata['X']
#XandY = mydata[['X','Y']]

A = mydata[(mydata['X']>2) & (mydata['Y']>2)]
B = mydata[(mydata['X']>18) | (mydata['Y']>10)]

print(mydata)

#Set Index
data = {
   'ages': [14, 18, 24, 42],
   'heights': [165, 180, 176, 184]
}
df_employee = pd.DataFrame(data, index=['James', 'Bob', 'Amy', 'Dave'])
print(df_employee)

#access data with index "James"
print(df_employee.loc["James"])

# third row
print(df_employee.iloc[2])
print("\n")
#first 3 rows
print(df_employee.iloc[:3])
print("\n")
# rows 2 to 3
print(df_employee.i1oc[1:3])

#Mount the Google Drive to Google Colab
from google.colab import drive
drive.mount('/content/gdrive')

#Reading data
import pandas as pd
mydata=pd.read_excel('/content/Penghasilan.xlsx')
mydata_csv = pd.read_csv('/content/Penghasilan.csv', names=['jumlahAnggotaKeluarga','penghasilan'], skiprows=1)

#indexing and slicing
#mydata_csv[mydata_csv.jumlahAnggotaKeluarga == 4]
#ydata_csv[mydata_csv.jumlahAnggotaKeluarga > 4]

#read data from local disk
#mydata = pd.read_csv("C:\\Users\\Deepanshu\\Documents\\file1.csv", header=None, names=['jumlahAnggotaKeluarga','penghasilan'], skiprows=1)

# import data from localdisk to google colab
from google.colab import files
uploaded = files.upload()

#Mount the Google Drive to Google Colab
from google.colab import drive
drive.mount('/content/gdrive')

#################################################
# VISUALIZATION WITH MATPLOTLIB
#################################################

import matplotlib.pyplot as plt

#Mount the Google Drive to Google Colab
from google.colab import drive
drive.mount('/content/gdrive')


x = [ 4,  5, 10,  4,  3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

#Scatter Plot
plt.scatter(x,y)


#Line Plot
fig = plt.figure(figsize=(6,6))
plt.plot(x,y, color='red', marker='o')
plt.title('Judul')
plt.xlabel('Sumbu-x')
plt.ylabel('Sumbu-y')
plt.ylim(0,30)
plt.xlim(0,15)
plt.savefig('/content/gdrive/MyDrive/GambarCoba.png')
plt.show()

#plot data from dataframe
import pandas as pd
data = {
   'ages': [14, 18, 24, 42],
   'heights': [165, 180, 176, 184]
}

df = pd.DataFrame(data, index=['James', 'Bob', 'Amy', 'Dave'])
df.plot()