# -*- coding: utf-8 -*-
"""Pertemuan3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C1MtJkHh8MAvax4EsAev_dRsAp0-pqZZ
"""

#Edited by: Muhardiansyah & Mutia Yollanda
#3nd Meeting
#Tuesday, November 1st 2022
#Introduction of Artificial Intelligence

import pandas as pd

from google.colab import drive
drive.mount('/content/mydrive')

import pandas as pd

mydata = pd.read_excel('/content/mydrive/MyDrive/Penghasilan.xlsx', names=['JumlahAnggotaKeluarga','Penghasilan'])

mydata

# Scatter plot
from matplotlib import pyplot as plt

plt.scatter(mydata.JumlahAnggotaKeluarga,mydata.Penghasilan)

# Data Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(mydata)
scaled = scaler.transform(mydata) #in array

scaled

from sklearn.cluster import KMeans

km = KMeans(n_clusters=3)
km.fit(scaled)
km.labels_

SSE = []
K = range(1,15)
for k in K:
    km = KMeans(n_clusters=k)
    km = km.fit(scaled)
    km.inertia_
    SSE.append(km.inertia_)

K = list(range(1,15))

plt.plot(K, SSE, 'o-')
plt.xlabel('k')
plt.ylabel('Sum_of_squared_distances')
plt.title('Elbow Method For Optimal k')
plt.show()

km = KMeans(n_clusters=3)
km = km.fit(scaled)
y_predicted = km.fit_predict(mydata)

mydata['cluster'] = y_predicted

mydata

plt.scatter(mydata.JumlahAnggotaKeluarga, mydata.Penghasilan, c=mydata.cluster)
plt.xlabel('Jumlah Anggota Keluarga')
plt.ylabel('Pengahsilan')
plt.title('Plot Hasil Clustering')
plt.show()

mydata1 = mydata[mydata.cluster==0]
mydata2 = mydata[mydata.cluster==1]
mydata3 = mydata[mydata.cluster==2]
 
plt.scatter(mydata1.JumlahAnggotaKeluarga,mydata1.Penghasilan, color='green')
plt.scatter(mydata2.JumlahAnggotaKeluarga,mydata2.Penghasilan, color='red')
plt.scatter(mydata3.JumlahAnggotaKeluarga,mydata3.Penghasilan, color='blue')
plt.xlabel('JumlahAnggotaKeluarga')
plt.ylabel('Penghasilan (juta rupiah)')
plt.grid()